# Generated by Django 5.0 on 2023-12-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='categoriaa',
        ),
    ]
