# Generated by Django 5.0 on 2023-12-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_estoque_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(choices=[('shape', 'Shape'), ('RD', 'roda'), ('RL', 'rolamento'), ('PR', 'parafuso'), ('TK', 'truck'), ('LX', 'lixa'), ('AS', 'acessorios')], max_length=30),
        ),
    ]
