# Generated by Django 5.0 on 2023-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_categoria_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(choices=[('shape', 'Shape'), ('roda', 'Roda'), ('rolamento', 'Rolamento'), ('parafuso', 'Amortecedor'), ('truck', 'Truck'), ('lixa', 'Lixa'), ('acessorios', 'Acessorios')], max_length=30),
        ),
    ]
